<section class="container mt-5">
   <div class="row">
      <div class="col-12">
         <h2>Documentación de ARCHPhp</h2>
         <p>La documentación de ARCHPhp está diseñada para ayudarte a comprender y utilizar el framework de manera
            efectiva. A continuación, se presentan las secciones principales de la documentación:</p>
      </div>
   </div>
   <div class="row mt-4">
      <div class="col-md-6">
         <h3>Guía de Inicio Rápido</h3>
         <p>Aprende a instalar y configurar ARCHPhp en pocos minutos.</p>
         <ul>
            <li><a href="#">Instalación</a></li>
            <li><a href="#">Configuración Inicial</a></li>
            <li><a href="#">Primeros Pasos</a></li>
         </ul>
      </div>
      <div class="col-md-6">
         <h3>Conceptos Básicos</h3>
         <p>Familiarízate con los conceptos fundamentales de ARCHPhp.</p>
         <ul>
            <li><a href="#">Arquitectura MVC</a></li>
            <li><a href="#">Ruteo</a></li>
            <li><a href="#">Controladores</a></li>
            <li><a href="#">Vistas</a></li>
            <li><a href="#">Modelos</a></li>
         </ul>
      </div>
   </div>
   <div class="row mt-4">
      <div class="col-md-6">
         <h3>Guías Avanzadas</h3>
         <p>Explora características avanzadas para proyectos más complejos.</p>
         <ul>
            <li><a href="#">Manejo de Sesiones</a></li>
            <li><a href="#">Autenticación y Autorización</a></li>
            <li><a href="#">Seguridad</a></li>
            <li><a href="#">Optimización de Desempeño</a></li>
            <li><a href="#">Uso de Middleware</a></li>
         </ul>
      </div>
      <div class="col-md-6">
         <h3>Recetas y Ejemplos</h3>
         <p>Encuentra ejemplos prácticos y recetas para tareas comunes.</p>
         <ul>
            <li><a href="#">Conexión a Bases de Datos</a></li>
            <li><a href="#">Envío de Correos Electrónicos</a></li>
            <li><a href="#">Subida de Archivos</a></li>
            <li><a href="#">Generación de PDF</a></li>
            <li><a href="#">Integración con APIs Externas</a></li>
         </ul>
      </div>
   </div>
   <div class="row mt-4">
      <div class="col-12">
         <h3>Referencia de API</h3>
         <p>Consulta la referencia completa de la API para obtener detalles sobre todas las clases y métodos disponibles
            en ARCHPhp.</p>
         <ul>
            <li><a href="#">Controladores</a></li>
            <li><a href="#">Modelos</a></li>
            <li><a href="#">Vistas</a></li>
            <li><a href="#">Utilidades</a></li>
         </ul>
      </div>
   </div>
</section>