<section class="container mt-5">
   <div class="row">
      <div class="col-md-6">
         <h2>Características de ARCHPhp</h2>
         <p>ARCHPhp está diseñado para hacer que el desarrollo web sea más rápido, más fácil y más eficiente. Aquí
            tienes algunas de las características clave:</p>
         <ul>
            <li><strong>Arquitectura MVC:</strong> Mantén tu código organizado y limpio con una arquitectura basada en
               Modelos, Vistas y Controladores.</li>
            <li><strong>Ruteo Avanzado:</strong> Define rutas amigables y personalizadas para tus aplicaciones.</li>
            <li><strong>Seguridad:</strong> Incluye herramientas integradas para proteger tus aplicaciones contra las
               amenazas comunes.</li>
            <li><strong>Plantillas:</strong> Utiliza un sistema de plantillas flexible para separar la lógica de la
               presentación.</li>
            <li><strong>Base de Datos:</strong> Integración sencilla con bases de datos populares como MySQL, PostgreSQL
               y SQLite.</li>
            <li><strong>Documentación Extensa:</strong> Encuentra guías, tutoriales y ejemplos detallados para ayudarte
               a empezar rápidamente.</li>
         </ul>
      </div>
      <div class="col-md-6">
         <h2>Beneficios de Usar ARCHPhp</h2>
         <p>ARCHPhp ofrece múltiples beneficios que te ayudarán a desarrollar tus proyectos de manera eficiente:</p>
         <ul>
            <li><strong>Fácil de Aprender:</strong> Ideal tanto para principiantes como para desarrolladores
               experimentados.</li>
            <li><strong>Modularidad:</strong> Añade o elimina componentes según tus necesidades.</li>
            <li><strong>Comunidad Activa:</strong> Únete a una comunidad de desarrolladores que comparten tus mismos
               intereses y objetivos.</li>
            <li><strong>Soporte:</strong> Recibe asistencia y soporte técnico de alta calidad.</li>
            <li><strong>Desempeño:</strong> Optimizado para ofrecer un rendimiento rápido y eficiente.</li>
            <li><strong>Compatibilidad:</strong> Compatible con múltiples plataformas y entornos de desarrollo.</li>
         </ul>
      </div>
   </div>
</section>