<!DOCTYPE html>
<html lang="es">

<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title><?= APP_NAME ?> - Inicio</title>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
         <a class="navbar-brand" href="<?= APP_URL ?>"><?= APP_NAME ?></a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
               <li class="nav-item">
                  <a class="nav-link" href="<?= APP_URL ?>main/home/index">Inicio</a>
               </li>
               <li class="nav-item">
                  <a class="nav-link" href="<?= APP_URL ?>main/home/caracteristicas">Características</a>
               </li>
               <li class="nav-item">
                  <a class="nav-link" href="<?= APP_URL ?>main/home/documentacion">Documentación</a>
               </li>
               <li class="nav-item">
                  <a class="nav-link" href="<?= APP_URL ?>main/home/contacto">Contacto</a>
               </li>
            </ul>
         </div>
      </div>
   </nav>

   <header class="jumbotron text-center">
      <div class="container">
         <h1 class="display-4">Bienvenido a <?= APP_NAME ?></h1>
         <p class="lead">Un marco robusto para el desarrollo en PHP</p>
         <a class="btn btn-primary btn-lg" href="#" role="button">Empezar</a>
      </div>
   </header>

   <section class="container mt-5">
      @content
   </section>

   <footer class="bg-light text-center py-4 mt-5">
      <p>&copy; 2024 <b><?= APP_NAME ?>.</b> Todos los derechos reservados.</p>
   </footer>


   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"></script>
</body>

</html>