<!-- <div class="row">
   <div class="col-md-4">
      <h2>Fácil de Usar</h2>
      <p>ARCHPhp está diseñado con la simplicidad en mente. Comienza rápido y fácilmente.</p>
   </div>
   <div class="col-md-4">
      <h2>Características Poderosas</h2>
      <p>Cargado con características para ayudarte a desarrollar aplicaciones web modernas de manera eficiente.
      </p>
   </div>
   <div class="col-md-4">
      <h2>Documentación Completa</h2>
      <p>Encuentra todo lo que necesitas en nuestra documentación detallada y extensa.</p>
   </div>
</div> -->

<div class="row">
   <div class="col-md-4">
      <div class="card mb-4 shadow-sm">
         <div class="card-body">
            <h5 class="card-title">Organización MVC</h5>
            <p class="card-text">Sigue el patrón Modelo-Vista-Controlador para una estructura organizada y modular.</p>
            <span class="feature-icon">&#128187;</span>
         </div>
      </div>
   </div>
   <div class="col-md-4">
      <div class="card mb-4 shadow-sm">
         <div class="card-body">
            <h5 class="card-title">Configuración flexible</h5>
            <p class="card-text">Personaliza fácilmente tu aplicación con variables de configuración.</p>
            <span class="feature-icon">&#9881;</span>
         </div>
      </div>
   </div>
   <div class="col-md-4">
      <div class="card mb-4 shadow-sm">
         <div class="card-body">
            <h5 class="card-title">Seguridad integrada</h5>
            <p class="card-text">Incluye características de seguridad para proteger tus datos sensibles.</p>
            <span class="feature-icon">&#128275;</span>
         </div>
      </div>
   </div>
</div>