<div class="row">
   <div class="col-md-4">
      <h2>Fácil de Usar</h2>
      <p>ARCHPhp está diseñado con la simplicidad en mente. Comienza rápido y fácilmente.</p>
   </div>
   <div class="col-md-4">
      <h2>Características Poderosas</h2>
      <p>Cargado con características para ayudarte a desarrollar aplicaciones web modernas de manera eficiente.
      </p>
   </div>
   <div class="col-md-4">
      <h2>Documentación Completa</h2>
      <p>Encuentra todo lo que necesitas en nuestra documentación detallada y extensa.</p>
   </div>
</div>